### ISSUE TITLE
question: are assertions out of scope?

### ISSUE THREAD

**Issue by jpuck** [ralouphie/mimey#10]
Now it's easy enough to check if an extension matches a media [*sub*type][1]

```php
$extension = 'mp4';
if ( $mimes->getMimeType($extension) === 'video/mp4' ) {
    // ...
}
```

Would you consider a PR to extend support for asserting media [*super*types][1]?

e.g.

```php
$extensions = [
    'mp4',
    'avi',
    'mkv',
];

foreach ( $extensions as $extension ) {
    if ( $mimes->isMediaType('video', $extension) ) {
        // returns true
    }
}
```

I understand that this is encroaching on the fringes of this lib's scope, but because it's such a standard use case, I was curious if you'd be open to it?

thanks

[1]:http://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by ralouphie** [comment]
Yes, I would consider this out of scope, this only aims to provide a simple mapping between MIME type and extension :)
