### ISSUE TITLE
Most common image/jpeg file extension

### ISSUE THREAD

**Issue by shtse8** [ralouphie/mimey#11]
At the moment, `mimey` best guess the extension of `image/jpeg` is `jpeg`. I think it's better to change to `jpg` as it should be the most common nowaday. 
Reference: http://stackoverflow.com/questions/23424399/jpg-vs-jpeg-image-formats

**Comment by spotman** [comment]
@ralouphie +1 for this! Or maybe it is possible to fix with custom mime-types bindings?

**Comment by ralouphie** [comment]
Thanks for the feedback. Added support in `2.0.0` via
https://github.com/ralouphie/mimey/commit/81e30eab608a582a6d7c293484fba0b34f3cf335#diff-121ebdf3a63c985502483d33a10e762b

**Comment by wrabit** [comment]
Just downloaded and out of the box it still returns jpeg instead of jpg
