### ISSUE TITLE
Support to image/x-ms-bmp 

### ISSUE THREAD

**Issue by masimao** [ralouphie/mimey#12]
`getExtension()` is returning `NULL` when mimetype is `image/x-ms-bmp `

**Comment by ralouphie** [comment]
Thanks for the feedback. Added support in `2.0.0` via
https://github.com/ralouphie/mimey/commit/81e30eab608a582a6d7c293484fba0b34f3cf335#diff-121ebdf3a63c985502483d33a10e762b
