### ISSUE TITLE
Support php file?

### ISSUE THREAD

**Issue by henriqueweiand** [ralouphie/mimey#14]
I tryed:

`$extension = $mimes->getExtension('text/x-php');`

But return NULL value. Extensions .php are not recognized?

EDIT
I getting mimetype with $file -> getMimeType() on laravel, // text/x-php

**Comment by ralouphie** [comment]
Thanks for the feedback. Added support in `2.0.0` via
https://github.com/ralouphie/mimey/commit/81e30eab608a582a6d7c293484fba0b34f3cf335#diff-121ebdf3a63c985502483d33a10e762b
