### ISSUE TITLE
Just a heads up

### ISSUE THREAD

**Issue by RobQuistNL** [ralouphie/mimey#5]
Mime types are _content_ types. A filename does not always describe the content of a file.

I could upload a .php file and name it .jpg - your class here will think its jpeg. Maybe even let me upload it.

You can (and should) use mime_content_type() to test properly... Just letting you know :)

**Comment by ralouphie** [comment]
That isn't the goal of this package. This isn't supposed to give you an absolute determination of a MIME type for a given file. It simply gives you the most common MIME type for a given extension and vice versa.

**Comment by RobQuistNL** [comment]
I know! Thats why I entitled it "heads up". Its not an issue though. Sorry
